 The three phases of data manipulation are
•	 Data preparation
•	 Data transformation
•	 Data aggregation

Data Preparation
•	 loading
•	 assembling
    •	 merging
    •	 concatenating
    •	 combining
•	 reshaping (pivoting)
•	 removing

In [1]:
import numpy as np
import pandas as pd
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
                        'price': [12.33,11.44,33.21,13.23,33.62]})
frame1

id  price
0     ball  12.33
1   pencil  11.44
2      pen  33.21
3      mug  13.23
4  ashtray  33.62

In [2]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
                        'color': ['white','red','red','black']})
frame2

id  color
0  pencil  white
1  pencil    red
2    ball    red
3     pen  black

In [3]:
pd.merge(frame1, frame2)

id  price  color
0    ball  12.33    red
1  pencil  11.44  white
2  pencil  11.44    red
3     pen  33.21  black

In [6]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
                        'color': ['white','red','red','black','green'],
                        'brand': ['OMG','ABC','ABC','POD','POD']})
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [7]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
                        'brand': ['OMG','POD','ABC','POD']})
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [8]:
pd.merge(frame1, frame2)

Empty DataFrame
Columns: [id, color, brand]
Index: []

So it is necessary to explicitly define the criterion of merging that pandas must follow, specifying the name of the key column in the on option. In fact, in most cases you need to decide which is the column on which to base the merging.

In [9]:
 pd.merge(frame1,frame2,on='id')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [10]:
pd.merge(frame1,frame2,on='brand')

id_x  color brand    id_y
0     ball  white   OMG  pencil
1   pencil    red   ABC    ball
2      pen    red   ABC    ball
3      mug  black   POD  pencil
4      mug  black   POD     pen
5  ashtray  green   POD  pencil
6  ashtray  green   POD     pen

In [24]:
frame2.columns = ['sid','brand']
frame2

sid brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [25]:
pd.merge(frame1, frame2, left_on='id', right_on='sid')

id  color brand_x     sid brand_y
0    ball  white     OMG    ball     ABC
1  pencil    red     ABC  pencil     OMG
2  pencil    red     ABC  pencil     POD
3     pen    red     ABC     pen     POD

In [26]:
frame2.columns = ['id','brand']
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [27]:
pd.merge(frame1,frame2,on='id',how='outer')

id  color brand_x brand_y
0     ball  white     OMG     ABC
1   pencil    red     ABC     OMG
2   pencil    red     ABC     POD
3      pen    red     ABC     POD
4      mug  black     POD     NaN
5  ashtray  green     POD     NaN

In [28]:
 pd.merge(frame1,frame2,on='id',how='left')

id  color brand_x brand_y
0     ball  white     OMG     ABC
1   pencil    red     ABC     OMG
2   pencil    red     ABC     POD
3      pen    red     ABC     POD
4      mug  black     POD     NaN
5  ashtray  green     POD     NaN

In [29]:
 pd.merge(frame1,frame2,on='id',how='right')

id  color brand_x brand_y
0  pencil    red     ABC     OMG
1  pencil    red     ABC     POD
2    ball  white     OMG     ABC
3     pen    red     ABC     POD

In [30]:
pd.merge(frame1,frame2,on=['id','brand'],how='outer')

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD
5   pencil    NaN   OMG
6   pencil    NaN   POD
7     ball    NaN   ABC
8      pen    NaN   POD

Merging on Index

In [31]:
pd.merge(frame1,frame2,right_index=True, left_index=True)


id_x  color brand_x    id_y brand_y
0    ball  white     OMG  pencil     OMG
1  pencil    red     ABC  pencil     POD
2     pen    red     ABC    ball     ABC
3     mug  black     POD     pen     POD

In [32]:
frame1.join(frame2)

ValueError: columns overlap but no suffix specified: Index(['id', 'brand'], dtype='object')

In [33]:
frame2.columns = ['brand2','id2']
frame1.join(frame2)

id  color brand  brand2  id2
0     ball  white   OMG  pencil  OMG
1   pencil    red   ABC  pencil  POD
2      pen    red   ABC    ball  ABC
3      mug  black   POD     pen  POD
4  ashtray  green   POD     NaN  NaN

Concatenating

In [39]:
array1 = np.arange(9).reshape(3,3)
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
array2 = np.arange(9).reshape((3,3))+6

In [41]:
array2

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [42]:
np.concatenate([array1,array2],axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [43]:
 np.concatenate([array1,array2],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [44]:
ser1 = pd.Series(np.random.rand(4), index=[1,2,3,4])

In [45]:
ser1

1    0.462992
2    0.300957
3    0.809066
4    0.245650
dtype: float64

In [46]:
ser2 = pd.Series(np.random.rand(4), index=[5,6,7,8])

In [47]:
ser2

5    0.246915
6    0.114552
7    0.323234
8    0.014702
dtype: float64

In [48]:
 pd.concat([ser1,ser2])

1    0.462992
2    0.300957
3    0.809066
4    0.245650
5    0.246915
6    0.114552
7    0.323234
8    0.014702
dtype: float64

In [49]:
pd.concat([ser1,ser2],axis=1)

0         1
1  0.462992       NaN
2  0.300957       NaN
3  0.809066       NaN
4  0.245650       NaN
5       NaN  0.246915
6       NaN  0.114552
7       NaN  0.323234
8       NaN  0.014702

In [51]:
pd.concat([ser1,ser2],axis=1,join='inner')

Empty DataFrame
Columns: [0, 1]
Index: []

In [52]:
pd.concat([ser1,ser2], keys=[1,2])

1  1    0.462992
   2    0.300957
   3    0.809066
   4    0.245650
2  5    0.246915
   6    0.114552
   7    0.323234
   8    0.014702
dtype: float64

In [53]:
 pd.concat([ser1,ser2], axis=1, keys=[1,2])

1         2
1  0.462992       NaN
2  0.300957       NaN
3  0.809066       NaN
4  0.245650       NaN
5       NaN  0.246915
6       NaN  0.114552
7       NaN  0.323234
8       NaN  0.014702

In [54]:
frame1 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[1,2,3], columns=['A','B','C'])
frame1

A         B         C
1  0.257267  0.175961  0.179971
2  0.950760  0.168894  0.567983
3  0.063330  0.779820  0.343168

In [55]:
frame2 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[4,5,6], columns=['A','B','C'])
frame2

A         B         C
4  0.460753  0.222684  0.498423
5  0.870598  0.692851  0.178824
6  0.159813  0.559370  0.662215

In [56]:
pd.concat([frame1, frame2], axis=1)

A         B         C         A         B         C
1  0.257267  0.175961  0.179971       NaN       NaN       NaN
2  0.950760  0.168894  0.567983       NaN       NaN       NaN
3  0.063330  0.779820  0.343168       NaN       NaN       NaN
4       NaN       NaN       NaN  0.460753  0.222684  0.498423
5       NaN       NaN       NaN  0.870598  0.692851  0.178824
6       NaN       NaN       NaN  0.159813  0.559370  0.662215

Combining

In [59]:
ser1 = pd.Series(np.random.rand(5),index=[1,2,3,4,5])
ser1

1    0.276134
2    0.667197
3    0.508317
4    0.494527
5    0.904826
dtype: float64

In [60]:
ser2 = pd.Series(np.random.rand(4),index=[2,4,5,6])
ser2

2    0.521410
4    0.462147
5    0.932987
6    0.136223
dtype: float64

In [61]:
 ser1.combine_first(ser2)

1    0.276134
2    0.667197
3    0.508317
4    0.494527
5    0.904826
6    0.136223
dtype: float64

In [62]:
ser2.combine_first(ser1)

1    0.276134
2    0.521410
3    0.508317
4    0.462147
5    0.932987
6    0.136223
dtype: float64

In [63]:
ser1[:3].combine_first(ser2[:3])

1    0.276134
2    0.667197
3    0.508317
4    0.462147
5    0.932987
dtype: float64

Pivoting with Hierarchical Indexing
•	 stacking: rotates or pivots the data structure converting columns to rows
•	 unstacking: converts rows into columns

Pivoting from “Long” to “Wide” Format

In [66]:
longframe = pd.DataFrame({ 'color':['white','white','white','red','red','red','black','black','black'],
                          'item':['ball','pen','mug','ball','pen','mug','ball','pen','mug'],
                          'value': np.random.rand(9)})
longframe

color  item     value
0  white  ball  0.464172
1  white   pen  0.462362
2  white   mug  0.981718
3    red  ball  0.497706
4    red   pen  0.598351
5    red   mug  0.468176
6  black  ball  0.307810
7  black   pen  0.829266
8  black   mug  0.767596

In [67]:
wideframe = longframe.pivot('color','item')

In [68]:
wideframe

value                    
item       ball       mug       pen
color                              
black  0.307810  0.767596  0.829266
red    0.497706  0.468176  0.598351
white  0.464172  0.981718  0.462362

Removing

In [70]:
frame1 = pd.DataFrame(np.arange(9).reshape(3,3),
                      index=['white','black','red'],
                      columns=['ball','pen','pencil'])
frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [71]:
del frame1['ball']

In [72]:
frame1

pen  pencil
white    1       2
black    4       5
red      7       8

In [74]:
frame1.drop('white')

pen  pencil
black    4       5
red      7       8

# Data Transformation


Removing Duplicates


In [77]:
dframe = pd.DataFrame({ 'color': ['white','white','red','red','white'],
                       'value': [2,1,3,3,2]})

In [78]:
dframe

color  value
0  white      2
1  white      1
2    red      3
3    red      3
4  white      2

In [79]:
dframe.duplicated()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [80]:
dframe[dframe.duplicated()]

color  value
3    red      3
4  white      2

In [85]:
dframe.drop_duplicates()

color  value
0  white      2
1  white      1
2    red      3

Mapping

•	 replace(): replaces values
•	 map(): creates a new column
•	 rename(): replaces the index values

Replacing Values via Mapping


In [86]:
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],
                      'color':['white','rosso','verde','black','yellow'],
                      'price':[5.56,4.20,1.30,0.56,2.75]})

In [87]:
frame

item   color  price
0     ball   white   5.56
1      mug   rosso   4.20
2      pen   verde   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [89]:
newcolors = {'rosso': 'red',
             'verde': 'green'
            }

In [90]:
frame.replace(newcolors)

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [91]:
ser = pd.Series([1,3,np.nan,4,6,np.nan,3])

In [92]:
ser 

0    1.0
1    3.0
2    NaN
3    4.0
4    6.0
5    NaN
6    3.0
dtype: float64

In [93]:
 ser.replace(np.nan,0)

0    1.0
1    3.0
2    0.0
3    4.0
4    6.0
5    0.0
6    3.0
dtype: float64

Adding Values via Mapping


In [94]:
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],
                      'color':['white','red','green','black','yellow']})
frame 

item   color
0     ball   white
1      mug     red
2      pen   green
3   pencil   black
4  ashtray  yellow

In [95]:
>>> price = {
... 'ball' : 5.56,
... 'mug' : 4.20,
... 'bottle' : 1.30,
... 'scissors' : 3.41,
... 'pen' : 1.30,
... 'pencil' : 0.56,
... 'ashtray' : 2.75
... }

In [97]:
frame['price'] = frame['item'].map(price)
frame 

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

Rename the Indexes of the Axes


In [98]:
frame 

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [99]:
>>> reindex = {
... 0: 'first',
... 1: 'second',
... 2: 'third',
... 3: 'fourth',
... 4: 'fifth'}
>>> frame.rename(reindex)

item   color  price
first      ball   white   5.56
second      mug     red   4.20
third       pen   green   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow   2.75

In [100]:
>>> recolumn = {
... 'item':'object',
... 'price': 'value'}
>>> frame.rename(index=reindex, columns=recolumn)

object   color  value
first      ball   white   5.56
second      mug     red   4.20
third       pen   green   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow   2.75

In [101]:
frame.rename(index={1:'first'}, columns={'item':'object'})

object   color  price
0         ball   white   5.56
first      mug     red   4.20
2          pen   green   1.30
3       pencil   black   0.56
4      ashtray  yellow   2.75

In [103]:
frame.rename(columns={'item':'object'}, inplace=True)
frame 

object   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

Discretization and Binning


In [104]:
results = [12,34,67,55,28,90,99,12,3,56,74,44,87,23,49,89,87]

In [105]:
 bins = [0,25,50,75,100]

In [106]:
cat = pd.cut(results, bins)
cat

[(0, 25], (25, 50], (50, 75], (50, 75], (25, 50], ..., (75, 100], (0, 25], (25, 50], (75, 100], (75, 100]]
Length: 17
Categories (4, interval[int64, right]): [(0, 25] < (25, 50] < (50, 75] < (75, 100]]

In [111]:
 pd.value_counts(cat)

(75, 100]    5
(0, 25]      4
(25, 50]     4
(50, 75]     4
dtype: int64

In [112]:
 bin_names = ['unlikely','less likely','likely','highly likely']

In [113]:
pd.cut(results, bins, labels=bin_names)

['unlikely', 'less likely', 'likely', 'likely', 'less likely', ..., 'highly likely', 'unlikely', 'less likely', 'highly likely', 'highly likely']
Length: 17
Categories (4, object): ['unlikely' < 'less likely' < 'likely' < 'highly likely']

In [114]:
pd.cut(results, 5)

[(2.904, 22.2], (22.2, 41.4], (60.6, 79.8], (41.4, 60.6], (22.2, 41.4], ..., (79.8, 99.0], (22.2, 41.4], (41.4, 60.6], (79.8, 99.0], (79.8, 99.0]]
Length: 17
Categories (5, interval[float64, right]): [(2.904, 22.2] < (22.2, 41.4] < (41.4, 60.6] < (60.6, 79.8] < (79.8, 99.0]]

In [115]:
quintiles = pd.qcut(results, 5)
quintiles

[(2.999, 24.0], (24.0, 46.0], (62.6, 87.0], (46.0, 62.6], (24.0, 46.0], ..., (62.6, 87.0], (2.999, 24.0], (46.0, 62.6], (87.0, 99.0], (62.6, 87.0]]
Length: 17
Categories (5, interval[float64, right]): [(2.999, 24.0] < (24.0, 46.0] < (46.0, 62.6] < (62.6, 87.0] < (87.0, 99.0]]

In [116]:
pd.value_counts(quintiles)


(2.999, 24.0]    4
(62.6, 87.0]     4
(24.0, 46.0]     3
(46.0, 62.6]     3
(87.0, 99.0]     3
dtype: int64

Detecting and Filtering Outliers


In [117]:
randframe = pd.DataFrame(np.random.randn(1000,3))

In [118]:
randframe.describe()

0            1            2
count  1000.000000  1000.000000  1000.000000
mean     -0.013592     0.064733     0.033581
std       0.974040     1.005875     1.032548
min      -3.075442    -2.917365    -3.774722
25%      -0.674051    -0.636034    -0.704475
50%      -0.033035     0.084933     0.001939
75%       0.690147     0.728083     0.781899
max       2.815480     2.932068     3.107932

In [120]:
randframe.std() # each column

0    0.974040
1    1.005875
2    1.032548
dtype: float64

In [121]:
randframe[(np.abs(randframe) > (3*randframe.std())).any(1)]

0         1         2
154 -3.075442  0.763709 -0.635382
254  0.234115  0.266220 -3.104302
572  1.561245  0.120570  3.107932
701 -0.123409  0.084935 -3.774722
858 -3.024266 -0.265674 -1.146800

Permutation


In [122]:
nframe = pd.DataFrame(np.arange(25).reshape(5,5))
nframe

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [123]:
new_order = np.random.permutation(5)
new_order

array([4, 1, 0, 3, 2])

In [124]:
nframe.take(new_order)

0   1   2   3   4
4  20  21  22  23  24
1   5   6   7   8   9
0   0   1   2   3   4
3  15  16  17  18  19
2  10  11  12  13  14

In [125]:
new_order = [3,4,2]
nframe.take(new_order)

0   1   2   3   4
3  15  16  17  18  19
4  20  21  22  23  24
2  10  11  12  13  14

Random Sampling


In [127]:
 sample = np.random.randint(0, len(nframe), size=3)

In [128]:
sample

array([0, 4, 4])

In [129]:
nframe.take(sample)

0   1   2   3   4
0   0   1   2   3   4
4  20  21  22  23  24
4  20  21  22  23  24

String Manipulation


In [130]:
 text = '16 Bolton Avenue , Boston'

In [131]:
text.split(',')

['16 Bolton Avenue ', ' Boston']

In [132]:
tokens = [s.strip() for s in text.split(',')]
tokens

['16 Bolton Avenue', 'Boston']

In [133]:
address, city = [s.strip() for s in text.split(',')]
address

'16 Bolton Avenue'

In [134]:
city

'Boston'

In [135]:
 address + ',' + city

'16 Bolton Avenue,Boston'

In [137]:
strings = ['A+','A','A-','B','BB','BBB','C+']
strings

['A+', 'A', 'A-', 'B', 'BB', 'BBB', 'C+']

In [138]:
';'.join(strings)

'A+;A;A-;B;BB;BBB;C+'

In [139]:
'Boston' in text

True

In [143]:
text.index('Boston')

19

In [144]:
text.find('Boston')

19

In [145]:
text.index('New York')

ValueError: substring not found

In [146]:
text.find('New York')

-1

In [147]:
 text.count('e')

2

In [148]:
text.count('Avenue')

1

In [149]:
text.replace('Avenue','Street')

'16 Bolton Street , Boston'

In [150]:
text.replace('1','')

'6 Bolton Avenue , Boston'

Regular Expressions


In [151]:
 import re

The re module provides a set of functions that can be divided into three different categories:
•	 pattern matching
•	 substitution
•	 splitting

In [152]:
text = "This is an\t odd \n text!"
re.split('\s+', text)


['This', 'is', 'an', 'odd', 'text!']

In [153]:
regex = re.compile('\s+')

In [154]:
regex.split(text)

['This', 'is', 'an', 'odd', 'text!']

In [155]:
text = 'This is my address: 16 Bolton Avenue, Boston'
text

'This is my address: 16 Bolton Avenue, Boston'

In [156]:
re.findall('A\w+',text)

['Avenue']

In [157]:
re.findall('[A,a]\w+',text)

['address', 'Avenue']

In [158]:
re.search('[A,a]\w+',text)

<re.Match object; span=(11, 18), match='address'>

In [159]:
search = re.search('[A,a]\w+',text)

In [160]:
 search.start()

11

In [161]:
 search.end()

18

In [162]:
text[search.start():search.end()]

'address'

In [163]:
re.match('[A,a]\w+',text)

In [164]:
re.match('T\w+',text)


<re.Match object; span=(0, 4), match='This'>

In [165]:
match = re.match('T\w+',text)

In [167]:
text[match.start():match.end()]

'This'

Data Aggregation


GroupBy

•	 splitting: division into groups of datasets
•	 applying: application of a function on each group
•	 combining: combination of all the results obtained by different groups

A Practical Example


In [170]:
frame = pd.DataFrame({ 'color': ['white','red','green','red','green'],
                      'object': ['pen','pencil','pencil','ashtray','pen'],
                      'price1' : [5.56,4.20,1.30,0.56,2.75],
                      'price2' : [4.75,4.12,1.60,0.75,3.15]})
frame

color   object  price1  price2
0  white      pen    5.56    4.75
1    red   pencil    4.20    4.12
2  green   pencil    1.30    1.60
3    red  ashtray    0.56    0.75
4  green      pen    2.75    3.15

In [175]:
group = frame['price1'].groupby(frame['color'])
group

In [176]:
group.groups

{'green': [2, 4], 'red': [1, 3], 'white': [0]}

In [177]:
group.mean()

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [178]:
group.sum()

color
green    4.05
red      4.76
white    5.56
Name: price1, dtype: float64

Hierarchical Grouping


In [179]:
ggroup = frame['price1'].groupby([frame['color'],frame['object']])


In [180]:
ggroup.groups

{('green', 'pen'): [4], ('green', 'pencil'): [2], ('red', 'ashtray'): [3], ('red', 'pencil'): [1], ('white', 'pen'): [0]}

In [181]:
ggroup.sum()

color  object 
green  pen        2.75
       pencil     1.30
red    ashtray    0.56
       pencil     4.20
white  pen        5.56
Name: price1, dtype: float64

In [182]:
frame[['price1','price2']].groupby(frame['color']).mean()

price1  price2
color                
green   2.025   2.375
red     2.380   2.435
white   5.560   4.750

In [183]:
frame.groupby(frame['color']).mean()

price1  price2
color                
green   2.025   2.375
red     2.380   2.435
white   5.560   4.750

Group Iteration


In [184]:
for name, group in frame.groupby('color'):
    print name
    print group

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(name)? (3715099019.py, line 2)

Chain of Transformations


In [185]:
result1 = frame['price1'].groupby(frame['color']).mean()
type(result1)

pandas.core.series.Series

In [186]:
result2 = frame.groupby(frame['color']).mean()
type(result2)

pandas.core.frame.DataFrame

In [187]:
frame['price1'].groupby(frame['color']).mean()

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [188]:
frame.groupby(frame['color'])['price1'].mean()

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [189]:
(frame.groupby(frame['color']).mean())['price1']

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [190]:
means = frame.groupby('color').mean().add_prefix('mean_')

In [191]:
means

mean_price1  mean_price2
color                          
green        2.025        2.375
red          2.380        2.435
white        5.560        4.750

Functions on Groups


In [192]:
group = frame.groupby('color')
group['price1'].quantile(0.6)

color
green    2.170
red      2.744
white    5.560
Name: price1, dtype: float64

In [193]:
def range(series):
    return series.max() - series.min()
group['price1'].agg(range)

color
green    1.45
red      3.64
white    0.00
Name: price1, dtype: float64

In [194]:
group.agg(range)


C:\Users\Ibrahim\AppData\Local\Temp\ipykernel_16968\2471387916.py:1: FutureWarning: ['object'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  group.agg(range)


price1  price2
color                
green    1.45    1.55
red      3.64    3.37
white    0.00    0.00

In [195]:
group['price1'].agg(['mean','std',range])


mean       std  range
color                        
green  2.025  1.025305   1.45
red    2.380  2.573869   3.64
white  5.560       NaN   0.00

Advanced Data Aggregation


In [197]:
frame = pd.DataFrame({ 'color':['white','red','green','red','green'],
                      'price1':[5.56,4.20,1.30,0.56,2.75],
                      'price2':[4.75,4.12,1.60,0.75,3.15]})
frame 

color  price1  price2
0  white    5.56    4.75
1    red    4.20    4.12
2  green    1.30    1.60
3    red    0.56    0.75
4  green    2.75    3.15

In [198]:
sums = frame.groupby('color').sum().add_prefix('tot_')
sums

tot_price1  tot_price2
color                        
green        4.05        4.75
red          4.76        4.87
white        5.56        4.75

In [203]:
pd.merge(frame,sums,left_on='color',right_index=True)


color  price1  price2  tot_price1  tot_price2
0  white    5.56    4.75        5.56        4.75
1    red    4.20    4.12        4.76        4.87
3    red    0.56    0.75        4.76        4.87
2  green    1.30    1.60        4.05        4.75
4  green    2.75    3.15        4.05        4.75

In [201]:
frame.groupby('color').transform(np.sum).add_prefix('tot_')


tot_price1  tot_price2
0        5.56        4.75
1        4.76        4.87
2        4.05        4.75
3        4.76        4.87
4        4.05        4.75

In [206]:
frame = pd.DataFrame( { 'color':['white','black','white','white','black','black'],
                    'status':['up','up','down','down','down','up'],
                    'value1':[12.33,14.55,22.34,27.84,23.40,18.33],
                    'value2':[11.23,31.80,29.99,31.18,18.25,22.44]})
frame 

color status  value1  value2
0  white     up   12.33   11.23
1  black     up   14.55   31.80
2  white   down   22.34   29.99
3  white   down   27.84   31.18
4  black   down   23.40   18.25
5  black     up   18.33   22.44

In [207]:
frame.groupby(['color','status']).apply( lambda x: x.max())


color status  value1  value2
color status                              
black down    black   down   23.40   18.25
      up      black     up   18.33   31.80
white down    white   down   27.84   31.18
      up      white     up   12.33   11.23

In [208]:
 frame.rename(index=reindex, columns=recolumn)

color status  value1  value2
first   white     up   12.33   11.23
second  black     up   14.55   31.80
third   white   down   22.34   29.99
fourth  white   down   27.84   31.18
fifth   black   down   23.40   18.25
5       black     up   18.33   22.44

In [211]:
temp = pd.date_range('1/1/2015', periods=10, freq= 'H')
temp 

DatetimeIndex(['2015-01-01 00:00:00', '2015-01-01 01:00:00',
               '2015-01-01 02:00:00', '2015-01-01 03:00:00',
               '2015-01-01 04:00:00', '2015-01-01 05:00:00',
               '2015-01-01 06:00:00', '2015-01-01 07:00:00',
               '2015-01-01 08:00:00', '2015-01-01 09:00:00'],
              dtype='datetime64[ns]', freq='H')

In [213]:
timeseries = pd.Series(np.random.rand(10), index=temp)

In [214]:
timeseries

2015-01-01 00:00:00    0.534681
2015-01-01 01:00:00    0.237067
2015-01-01 02:00:00    0.356361
2015-01-01 03:00:00    0.266305
2015-01-01 04:00:00    0.836585
2015-01-01 05:00:00    0.591967
2015-01-01 06:00:00    0.207226
2015-01-01 07:00:00    0.067492
2015-01-01 08:00:00    0.212887
2015-01-01 09:00:00    0.179848
Freq: H, dtype: float64

In [217]:
timetable = pd.DataFrame( {'date': temp, 'value1' : np.random.rand(10),
                        'value2' : np.random.rand(10)})
timetable

date    value1    value2
0 2015-01-01 00:00:00  0.869285  0.295236
1 2015-01-01 01:00:00  0.490046  0.448922
2 2015-01-01 02:00:00  0.625778  0.928969
3 2015-01-01 03:00:00  0.763751  0.068508
4 2015-01-01 04:00:00  0.619233  0.841372
5 2015-01-01 05:00:00  0.543192  0.441709
6 2015-01-01 06:00:00  0.884296  0.017221
7 2015-01-01 07:00:00  0.464727  0.455814
8 2015-01-01 08:00:00  0.255604  0.849290
9 2015-01-01 09:00:00  0.095700  0.234608

In [218]:
timetable['cat'] = ['up','down','left','left','up','up','down','right','right','up']
timetable

date    value1    value2    cat
0 2015-01-01 00:00:00  0.869285  0.295236     up
1 2015-01-01 01:00:00  0.490046  0.448922   down
2 2015-01-01 02:00:00  0.625778  0.928969   left
3 2015-01-01 03:00:00  0.763751  0.068508   left
4 2015-01-01 04:00:00  0.619233  0.841372     up
5 2015-01-01 05:00:00  0.543192  0.441709     up
6 2015-01-01 06:00:00  0.884296  0.017221   down
7 2015-01-01 07:00:00  0.464727  0.455814  right
8 2015-01-01 08:00:00  0.255604  0.849290  right
9 2015-01-01 09:00:00  0.095700  0.234608     up