# Chapter 3 ■ The NumPy Library


In [1]:
# Ndarray: The Heart of the Library

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3]) # function

In [4]:
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [9]:
a.dtype # attribute

dtype('int32')

In [10]:
a.ndim

1

In [11]:
a.size

3

In [12]:
a.shape

(3,)

In [3]:
b = np.array([[1.3, 2.4],[0.3, 4.1]])
b

array([[1.3, 2.4],
       [0.3, 4.1]])

In [14]:
b.dtype

dtype('float64')

In [15]:
b.ndim

2

In [16]:
b.size

4

In [17]:
b.shape

(2, 2)

In [18]:
b.itemsize

8

In [19]:
b.data

In [20]:
# Create an array

In [21]:
 c = np.array([[1, 2, 3],[4, 5, 6]]) # LIST


In [22]:
 c 

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
d = np.array(((1, 2, 3),(4, 5, 6))) # TUPLE

In [24]:
d 

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)]) # Sequence and list
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
# Types of Data

In [29]:
g = np.array([['a', 'b'],['c', 'd']])

In [30]:
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [31]:
g.dtype

dtype('<U1')

In [32]:
g.dtype

dtype('<U1')

In [33]:
g.dtype.name

'str32'

In [34]:
# The dtype Option
f = np.array([[1, 2, 3],[4, 5, 6]], dtype=complex)

In [35]:
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [36]:
# Intrinsic Creation of an Array
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
 np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [40]:
np.arange(0, 12, 3)

array([0, 3, 6, 9])

In [41]:
np.arange(0, 6, 0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [42]:
 np.arange(0, 12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [44]:
np.random.random(3)

array([0.9408918 , 0.52364885, 0.71109996])

In [45]:
 np.random.random((3,3))

array([[0.3664393 , 0.01152107, 0.12169257],
       [0.75569888, 0.65433735, 0.11482765],
       [0.43771738, 0.31314801, 0.12962741]])

In [46]:
# Basic Operations

In [47]:
 a = np.arange(4)

In [48]:
a

array([0, 1, 2, 3])

In [49]:
a+4

array([4, 5, 6, 7])

In [50]:
a*1

array([0, 1, 2, 3])

In [53]:
b = np.arange(4,8)
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [54]:
 a * np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

In [55]:
A = np.arange(0, 9).reshape(3, 3)

In [56]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
B = np.ones((3, 3))
B 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [58]:
# The Matrix Product
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [59]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [60]:
 np.dot(B,A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

In [61]:
# Increment and Decrement Operators
a = np.arange(4)
a 

array([0, 1, 2, 3])

In [62]:
a+=1

In [63]:
a

array([1, 2, 3, 4])

In [64]:
# Universal Functions (ufunc)
a = np.arange(1, 5)
a 

array([1, 2, 3, 4])

In [66]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [68]:
np.log(a) 

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [69]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [71]:
# Aggregate Functions
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
a.sum()

15.0

In [72]:
a.min()

0.3

In [74]:
a.max()

5.7

In [75]:
a.mean()

3.0

In [76]:
a.std()

2.0079840636817816

In [77]:
# Indexing, Slicing, and Iterating

In [1]:
# Indexing
a = np.arange(10, 16)

In [2]:
a

array([10, 11, 12, 13, 14, 15])

In [3]:
a[4]

14

In [8]:
a[-1]

15

In [9]:
a[[1, 3, 4]]

array([11, 13, 14])

In [10]:
A = np.arange(10, 19).reshape((3, 3))
A 

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [11]:
A[1, 2]

15

In [12]:
# Slicing
a = np.arange(10, 16)
a     

array([10, 11, 12, 13, 14, 15])

In [13]:
a[1:4]

array([11, 12, 13])

In [14]:
a[1:5:2]

array([11, 13])

In [15]:
a[::2]

array([10, 12, 14])

In [16]:
A = np.arange(10, 19).reshape((3, 3))

In [17]:
A 

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [18]:
A[0,:] # First row

array([10, 11, 12])

In [19]:
A[:,0] # First column

array([10, 13, 16])

In [20]:
 A[0:2, 0:2]

array([[10, 11],
       [13, 14]])

In [21]:
>>> A[[0,2], 0:2]


array([[10, 11],
       [16, 17]])

In [23]:
# Iterating an Array
for i in a:
    print(i) 

10
11
12
13
14
15


In [24]:
for row in A:
    print(row)

[10 11 12]
[13 14 15]
[16 17 18]


In [25]:
for item in A.flat:
    print(item)

10
11
12
13
14
15
16
17
18


In [26]:
np.apply_along_axis(np.mean, axis=0, arr=A)

array([13., 14., 15.])

In [27]:
np.apply_along_axis(np.mean, axis=1, arr=A)

array([11., 14., 17.])

In [28]:
def foo(x):
    return x/2
np.apply_along_axis(foo, axis=1, arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

In [30]:
np.apply_along_axis(foo, axis=1, arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

# Conditions and Boolean Arrays

In [33]:
A = np.random.random((4,4))

In [34]:
A

array([[0.53879086, 0.45135673, 0.13475879, 0.17322449],
       [0.20452607, 0.67041248, 0.07513334, 0.4393965 ],
       [0.96204184, 0.27808007, 0.10832915, 0.78455956],
       [0.16367085, 0.99495139, 0.00597525, 0.94126475]])

In [35]:
A < 0.5

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [False,  True,  True, False],
       [ True, False,  True, False]])

In [36]:
>>> A[A < 0.5]

array([0.45135673, 0.13475879, 0.17322449, 0.20452607, 0.07513334,
       0.4393965 , 0.27808007, 0.10832915, 0.16367085, 0.00597525])

In [37]:
# Shape Manipulation


In [39]:
a = np.random.random(12)

In [40]:
a 

array([0.64802479, 0.56000703, 0.85476123, 0.3978608 , 0.41021974,
       0.434435  , 0.79185946, 0.52598173, 0.61085348, 0.43832772,
       0.36619174, 0.30894001])

In [41]:
A = a.reshape(3, 4)

In [42]:
A

array([[0.64802479, 0.56000703, 0.85476123, 0.3978608 ],
       [0.41021974, 0.434435  , 0.79185946, 0.52598173],
       [0.61085348, 0.43832772, 0.36619174, 0.30894001]])

In [43]:
a.shape = (3, 4)
a 

array([[0.64802479, 0.56000703, 0.85476123, 0.3978608 ],
       [0.41021974, 0.434435  , 0.79185946, 0.52598173],
       [0.61085348, 0.43832772, 0.36619174, 0.30894001]])

In [44]:
a = a.ravel() # 2d to 1d array

In [45]:
a

array([0.64802479, 0.56000703, 0.85476123, 0.3978608 , 0.41021974,
       0.434435  , 0.79185946, 0.52598173, 0.61085348, 0.43832772,
       0.36619174, 0.30894001])

In [46]:
a.shape = (12)
a 

array([0.64802479, 0.56000703, 0.85476123, 0.3978608 , 0.41021974,
       0.434435  , 0.79185946, 0.52598173, 0.61085348, 0.43832772,
       0.36619174, 0.30894001])

In [47]:
A.transpose()

array([[0.64802479, 0.41021974, 0.61085348],
       [0.56000703, 0.434435  , 0.43832772],
       [0.85476123, 0.79185946, 0.36619174],
       [0.3978608 , 0.52598173, 0.30894001]])

In [48]:
# Array Manipulation

In [49]:
# Joining Arrays
A = np.ones((3, 3))
B = np.zeros((3, 3))
np.vstack((A,B))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
np.hstack((A,B))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [51]:
>>> a = np.array([0, 1, 2])
>>> b = np.array([3, 4, 5])
>>> c = np.array([6, 7, 8])

In [52]:
np.column_stack((a,b,c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [53]:
np.row_stack((a,b,c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
# Splitting Arrays
>>> A = np.arange(16).reshape((4, 4))

In [55]:
A 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
>>> [B,C] = np.hsplit(A, 2)

In [57]:
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [58]:
C 

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [59]:
[B,C] = np.vsplit(A, 2)
B 

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [60]:
C 

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
[A1,A2,A3] = np.split(A,[1,3],axis=1)
A1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [62]:
A2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [63]:
A3

array([[ 3],
       [ 7],
       [11],
       [15]])

In [64]:
>>> [A1,A2,A3] = np.split(A,[1,3],axis=0)
>>> A1

array([[0, 1, 2, 3]])

In [65]:
A2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
A3

array([[12, 13, 14, 15]])

In [67]:
# General Concepts

In [70]:
# Copies or Views of Objects
a = np.array([1, 2, 3, 4])
b=a 
a 

array([1, 2, 3, 4])

In [73]:
a[2] = 0
b 

array([1, 2, 0, 4])

In [74]:
c = a[0:2]
c 

array([1, 2])

In [75]:
a[0] = 0

In [76]:
c 

array([0, 2])

In [77]:
a = np.array([1, 2, 3, 4])
c = a.copy()   

In [78]:
c

array([1, 2, 3, 4])

In [79]:
a[0] = 0
c 

array([1, 2, 3, 4])

In [80]:
# Vectorization
a*b 


array([ 0,  4,  0, 16])

In [81]:
>>> m = np.arange(6).reshape(3, 1, 2)
>>> n = np.arange(6).reshape(3, 2, 1)
>>> m

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [82]:
n

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

In [83]:
# Structured Arrays

In [84]:
>>> structured = np.array([(1, 'First', 0.5, 1+2j),(2, 'Second', 1.3, 2-2j), 
(3, 'Third', 0.8, 1+3j)],dtype=('i2, a6, f4, c8'))

In [85]:
structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [87]:
structured = np.array([(1, 'First', 0.5, 1+2j),(2, 'Second', 1.3,2-2j), (3, 'Third', 0.8, 1+3j)],dtype=('int16, a6, float32, complex64'))

In [88]:
structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [89]:
 structured[1]

(2, b'Second', 1.3, 2.-2.j)

In [91]:
structured['f1']=np.array(['First', 'Second', 'Third'],dtype='|S6')

In [92]:
structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [93]:
structured = np.array([(1,'First',0.5,1+2j),(2,'Second',1.3,2-2j),(3,'Third',0.8,1+3j)],
dtype=[('id','i2'),('position','a6'),('value','f4'),('complex','c8')])

In [94]:
structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('id', '<i2'), ('position', 'S6'), ('value', '<f4'), ('complex', '<c8')])

In [95]:
structured.dtype.names = ('id','order','value','complex')

In [104]:
# Reading and Writing Array Data on Files
data = np.random.random((3,3))
data

array([[0.07299972, 0.11151036, 0.03791054],
       [0.53527546, 0.3093827 , 0.8596488 ],
       [0.88671843, 0.9792449 , 0.83836944]])

In [105]:
 np.save('saved_data',data)

In [106]:
>>> loaded_data = np.load('saved_data.npy')
>>> loaded_data

array([[0.07299972, 0.11151036, 0.03791054],
       [0.53527546, 0.3093827 , 0.8596488 ],
       [0.88671843, 0.9792449 , 0.83836944]])

In [110]:
data1 = np.genfromtxt('Lottery Singapore Dataset.txt', delimiter='/t')
data1

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan])